import { createFileRoute } from "@tanstack/react-router";
import { FooterPageLayout } from "@/landingpage-ui/FooterPageLayout";

export const Route = createFileRoute("/footer-pages/about")({
  component: AboutPage,
});

function AboutPage() {
  return (
    <FooterPageLayout
      title="About Studiqs"
      subtitle="Smarter Educational Decisions Through Intelligence"
    >
      <div className="space-y-8 text-[15.5px] leading-[1.8] text-[#2a2a2a]/85">
        <p>
          Studiqs is an educational intelligence platform designed to help schools transform academic data into meaningful insights that support students, teachers, parents, and school leadership.
        </p>
        <p>
          Rather than functioning as a traditional ERP or Learning Management System, Studiqs focuses on educational intelligence — enabling institutions to understand learning patterns, identify academic risks, monitor progress trends, and support better educational outcomes through data-driven insights.
        </p>

        <h3 className="font-display text-[22px] font-bold text-[#161616] mt-8">Our Vision</h3>
        <p>
          To make educational decision-making more informed, proactive, and meaningful for every student, teacher, parent, and institution.
        </p>

        <h3 className="font-display text-[22px] font-bold text-[#161616] mt-8">Our Mission</h3>
        <ul className="list-disc pl-6 space-y-2">
          <li>To simplify educational analytics for schools.</li>
          <li>To help educators identify opportunities for early intervention and support.</li>
          <li>To provide parents with greater visibility into student progress.</li>
          <li>To enable school leadership with actionable academic intelligence.</li>
          <li>To promote data-informed educational decisions across institutions.</li>
        </ul>

        <h3 className="font-display text-[22px] font-bold text-[#161616] mt-8">What Makes Studiqs Different</h3>
        <p>
          Studiqs is built around educational intelligence rather than administrative management. The platform focuses on:
        </p>
        <ul className="list-disc pl-6 space-y-2">
          <li>Academic performance intelligence</li>
          <li>Learning trend analysis</li>
          <li>Risk identification and early intervention indicators</li>
          <li>Topic and concept understanding analysis</li>
          <li>Institutional performance insights</li>
          <li>Actionable educational recommendations</li>
        </ul>

        <h3 className="font-display text-[22px] font-bold text-[#161616] mt-8">Designed For</h3>
        <p>Studiqs is designed to support:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>School Leadership Teams</li>
          <li>Teachers and Coordinators</li>
          <li>Parents and Guardians</li>
          <li>Students</li>
        </ul>

        <h3 className="font-display text-[22px] font-bold text-[#161616] mt-8">Responsible Use of Intelligence</h3>
        <p>
          Studiqs provides educational insights intended to assist and support decision-making processes within schools and families. Educational recommendations generated by the platform are advisory in nature and should be considered alongside professional judgment and institutional policies.
        </p>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mt-8">
          <div className="border border-[#1a1a1a]/8 rounded-2xl bg-white p-6 shadow-sm">
            <h4 className="font-bold text-[#161616] font-display">✳︎ Leadership</h4>
            <p className="text-[15px] mt-2 text-[#2a2a2a]/85 font-medium">Ahamed Ashieq A, B.E., MBA., MS</p>
            <p className="text-[13px] text-[#2a2a2a]/70">Founder & CEO</p>
            <p className="text-[13px] text-[#2a2a2a]/70">Studiqs Intelligence LLP</p>
          </div>

          <div className="border border-[#1a1a1a]/8 rounded-2xl bg-white p-6 shadow-sm">
            <h4 className="font-bold text-[#161616] font-display">✳︎ Contact</h4>
            <p className="text-[13.5px] mt-2 text-[#2a2a2a]/75">
              For general enquiries, partnerships, or support requests:
            </p>
            <a href="mailto:contact@studiqs.com" className="mt-2 inline-block text-[15px] font-semibold text-[#c97a3a] hover:underline">
              contact@studiqs.com
            </a>
          </div>
        </div>
      </div>
    </FooterPageLayout>
  );
}
