import { createFileRoute } from "@tanstack/react-router";
import { FooterPageLayout } from "@/landingpage-ui/FooterPageLayout";

export const Route = createFileRoute("/footer-pages/faq")({
  component: FAQPage,
});

const FAQS = [
  {
    q: "What is Studiqs?",
    a: "Studiqs is an educational intelligence platform that helps schools transform academic data into meaningful insights for students, educators, parents, and school leadership.",
  },
  {
    q: "Is Studiqs an ERP or Learning Management System?",
    a: "No. Studiqs is designed to complement existing school systems by providing educational insights and intelligence that support decision-making and student outcomes.",
  },
  {
    q: "Who can use Studiqs?",
    a: "Studiqs is designed for School Leadership Teams, Teachers and Coordinators, Parents and Guardians, and Students.",
  },
  {
    q: "Does the school retain ownership of its data?",
    a: "Yes. Schools retain ownership of their institutional, staff, parent, and student information. Studiqs acts solely as a technology service provider processing information to deliver platform services.",
  },
  {
    q: "How is student information protected?",
    a: "Studiqs follows responsible data handling practices and uses secure infrastructure designed to protect educational information and restrict access to authorized users only.",
  },
  {
    q: "Does Studiqs provide academic recommendations?",
    a: "Studiqs may provide educational insights, recommendations, risk indicators, and trend analysis intended to support educational decision-making.",
  },
  {
    q: "Are Studiqs recommendations final decisions?",
    a: "No. Recommendations and insights generated by Studiqs are advisory in nature and should be considered alongside professional judgment and institutional policies.",
  },
  {
    q: "Is implementation support provided?",
    a: "Yes. The Studiqs team provides onboarding assistance and implementation support to help institutions adopt the platform effectively.",
  },
];

function FAQPage() {
  return (
    <FooterPageLayout
      title="Frequently Asked Questions"
      subtitle="Find answers to common questions about Studiqs deployment and features."
    >
      <div className="space-y-8 text-[15px] leading-[1.7] text-[#2a2a2a]/85">
        <p>
          Can't find what you're looking for? Reach out to our school support team at{" "}
          <a href="mailto:contact@studiqs.com" className="text-[#c97a3a] hover:underline font-semibold">
            contact@studiqs.com
          </a>
          .
        </p>

        <div className="space-y-6 mt-8">
          {FAQS.map((f, idx) => (
            <div key={idx} className="border-b border-[#1a1a1a]/8 pb-6">
              <h3 className="font-display text-[17px] font-bold text-[#161616]">
                ✳︎ {f.q}
              </h3>
              <p className="mt-3 text-[14px] text-[#2a2a2a]/75 leading-relaxed pl-6">
                {f.a}
              </p>
            </div>
          ))}
        </div>
      </div>
    </FooterPageLayout>
  );
}
