/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FooterPagesSupportRouteImport } from './routes/footer-pages/support'
import { Route as FooterPagesSecurityRouteImport } from './routes/footer-pages/security'
import { Route as FooterPagesPricingRouteImport } from './routes/footer-pages/pricing'
import { Route as FooterPagesModulesRouteImport } from './routes/footer-pages/modules'
import { Route as FooterPagesFeaturesRouteImport } from './routes/footer-pages/features'
import { Route as FooterPagesFaqRouteImport } from './routes/footer-pages/faq'
import { Route as FooterPagesDocumentationRouteImport } from './routes/footer-pages/documentation'
import { Route as FooterPagesContactRouteImport } from './routes/footer-pages/contact'
import { Route as FooterPagesCareersRouteImport } from './routes/footer-pages/careers'
import { Route as FooterPagesAboutRouteImport } from './routes/footer-pages/about'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FooterPagesSupportRoute = FooterPagesSupportRouteImport.update({
  id: '/footer-pages/support',
  path: '/footer-pages/support',
  getParentRoute: () => rootRouteImport,
} as any)
const FooterPagesSecurityRoute = FooterPagesSecurityRouteImport.update({
  id: '/footer-pages/security',
  path: '/footer-pages/security',
  getParentRoute: () => rootRouteImport,
} as any)
const FooterPagesPricingRoute = FooterPagesPricingRouteImport.update({
  id: '/footer-pages/pricing',
  path: '/footer-pages/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const FooterPagesModulesRoute = FooterPagesModulesRouteImport.update({
  id: '/footer-pages/modules',
  path: '/footer-pages/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const FooterPagesFeaturesRoute = FooterPagesFeaturesRouteImport.update({
  id: '/footer-pages/features',
  path: '/footer-pages/features',
  getParentRoute: () => rootRouteImport,
} as any)
const FooterPagesFaqRoute = FooterPagesFaqRouteImport.update({
  id: '/footer-pages/faq',
  path: '/footer-pages/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FooterPagesDocumentationRoute =
  FooterPagesDocumentationRouteImport.update({
    id: '/footer-pages/documentation',
    path: '/footer-pages/documentation',
    getParentRoute: () => rootRouteImport,
  } as any)
const FooterPagesContactRoute = FooterPagesContactRouteImport.update({
  id: '/footer-pages/contact',
  path: '/footer-pages/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FooterPagesCareersRoute = FooterPagesCareersRouteImport.update({
  id: '/footer-pages/careers',
  path: '/footer-pages/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const FooterPagesAboutRoute = FooterPagesAboutRouteImport.update({
  id: '/footer-pages/about',
  path: '/footer-pages/about',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/footer-pages/about': typeof FooterPagesAboutRoute
  '/footer-pages/careers': typeof FooterPagesCareersRoute
  '/footer-pages/contact': typeof FooterPagesContactRoute
  '/footer-pages/documentation': typeof FooterPagesDocumentationRoute
  '/footer-pages/faq': typeof FooterPagesFaqRoute
  '/footer-pages/features': typeof FooterPagesFeaturesRoute
  '/footer-pages/modules': typeof FooterPagesModulesRoute
  '/footer-pages/pricing': typeof FooterPagesPricingRoute
  '/footer-pages/security': typeof FooterPagesSecurityRoute
  '/footer-pages/support': typeof FooterPagesSupportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/footer-pages/about': typeof FooterPagesAboutRoute
  '/footer-pages/careers': typeof FooterPagesCareersRoute
  '/footer-pages/contact': typeof FooterPagesContactRoute
  '/footer-pages/documentation': typeof FooterPagesDocumentationRoute
  '/footer-pages/faq': typeof FooterPagesFaqRoute
  '/footer-pages/features': typeof FooterPagesFeaturesRoute
  '/footer-pages/modules': typeof FooterPagesModulesRoute
  '/footer-pages/pricing': typeof FooterPagesPricingRoute
  '/footer-pages/security': typeof FooterPagesSecurityRoute
  '/footer-pages/support': typeof FooterPagesSupportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/footer-pages/about': typeof FooterPagesAboutRoute
  '/footer-pages/careers': typeof FooterPagesCareersRoute
  '/footer-pages/contact': typeof FooterPagesContactRoute
  '/footer-pages/documentation': typeof FooterPagesDocumentationRoute
  '/footer-pages/faq': typeof FooterPagesFaqRoute
  '/footer-pages/features': typeof FooterPagesFeaturesRoute
  '/footer-pages/modules': typeof FooterPagesModulesRoute
  '/footer-pages/pricing': typeof FooterPagesPricingRoute
  '/footer-pages/security': typeof FooterPagesSecurityRoute
  '/footer-pages/support': typeof FooterPagesSupportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/footer-pages/about'
    | '/footer-pages/careers'
    | '/footer-pages/contact'
    | '/footer-pages/documentation'
    | '/footer-pages/faq'
    | '/footer-pages/features'
    | '/footer-pages/modules'
    | '/footer-pages/pricing'
    | '/footer-pages/security'
    | '/footer-pages/support'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/footer-pages/about'
    | '/footer-pages/careers'
    | '/footer-pages/contact'
    | '/footer-pages/documentation'
    | '/footer-pages/faq'
    | '/footer-pages/features'
    | '/footer-pages/modules'
    | '/footer-pages/pricing'
    | '/footer-pages/security'
    | '/footer-pages/support'
  id:
    | '__root__'
    | '/'
    | '/footer-pages/about'
    | '/footer-pages/careers'
    | '/footer-pages/contact'
    | '/footer-pages/documentation'
    | '/footer-pages/faq'
    | '/footer-pages/features'
    | '/footer-pages/modules'
    | '/footer-pages/pricing'
    | '/footer-pages/security'
    | '/footer-pages/support'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FooterPagesAboutRoute: typeof FooterPagesAboutRoute
  FooterPagesCareersRoute: typeof FooterPagesCareersRoute
  FooterPagesContactRoute: typeof FooterPagesContactRoute
  FooterPagesDocumentationRoute: typeof FooterPagesDocumentationRoute
  FooterPagesFaqRoute: typeof FooterPagesFaqRoute
  FooterPagesFeaturesRoute: typeof FooterPagesFeaturesRoute
  FooterPagesModulesRoute: typeof FooterPagesModulesRoute
  FooterPagesPricingRoute: typeof FooterPagesPricingRoute
  FooterPagesSecurityRoute: typeof FooterPagesSecurityRoute
  FooterPagesSupportRoute: typeof FooterPagesSupportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/footer-pages/support': {
      id: '/footer-pages/support'
      path: '/footer-pages/support'
      fullPath: '/footer-pages/support'
      preLoaderRoute: typeof FooterPagesSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/footer-pages/security': {
      id: '/footer-pages/security'
      path: '/footer-pages/security'
      fullPath: '/footer-pages/security'
      preLoaderRoute: typeof FooterPagesSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/footer-pages/pricing': {
      id: '/footer-pages/pricing'
      path: '/footer-pages/pricing'
      fullPath: '/footer-pages/pricing'
      preLoaderRoute: typeof FooterPagesPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/footer-pages/modules': {
      id: '/footer-pages/modules'
      path: '/footer-pages/modules'
      fullPath: '/footer-pages/modules'
      preLoaderRoute: typeof FooterPagesModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/footer-pages/features': {
      id: '/footer-pages/features'
      path: '/footer-pages/features'
      fullPath: '/footer-pages/features'
      preLoaderRoute: typeof FooterPagesFeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/footer-pages/faq': {
      id: '/footer-pages/faq'
      path: '/footer-pages/faq'
      fullPath: '/footer-pages/faq'
      preLoaderRoute: typeof FooterPagesFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/footer-pages/documentation': {
      id: '/footer-pages/documentation'
      path: '/footer-pages/documentation'
      fullPath: '/footer-pages/documentation'
      preLoaderRoute: typeof FooterPagesDocumentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/footer-pages/contact': {
      id: '/footer-pages/contact'
      path: '/footer-pages/contact'
      fullPath: '/footer-pages/contact'
      preLoaderRoute: typeof FooterPagesContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/footer-pages/careers': {
      id: '/footer-pages/careers'
      path: '/footer-pages/careers'
      fullPath: '/footer-pages/careers'
      preLoaderRoute: typeof FooterPagesCareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/footer-pages/about': {
      id: '/footer-pages/about'
      path: '/footer-pages/about'
      fullPath: '/footer-pages/about'
      preLoaderRoute: typeof FooterPagesAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FooterPagesAboutRoute: FooterPagesAboutRoute,
  FooterPagesCareersRoute: FooterPagesCareersRoute,
  FooterPagesContactRoute: FooterPagesContactRoute,
  FooterPagesDocumentationRoute: FooterPagesDocumentationRoute,
  FooterPagesFaqRoute: FooterPagesFaqRoute,
  FooterPagesFeaturesRoute: FooterPagesFeaturesRoute,
  FooterPagesModulesRoute: FooterPagesModulesRoute,
  FooterPagesPricingRoute: FooterPagesPricingRoute,
  FooterPagesSecurityRoute: FooterPagesSecurityRoute,
  FooterPagesSupportRoute: FooterPagesSupportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
